/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import {useGLTF} from '@react-three/drei'

export function SensorD(props: any) {
    const {nodes, materials}: any = useGLTF('/model/bdtec/Sensor_D.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                name="tripo_node_b961efe2-86a3-4639-af6a-cabdb034c05b"
                castShadow
                receiveShadow
                geometry={nodes['tripo_node_b961efe2-86a3-4639-af6a-cabdb034c05b'].geometry}
                material={materials['tripo_node_b961efe2-86a3-4639-af6a-cabdb034c05b_material']}
                userData={{ name: 'tripo_node_b961efe2-86a3-4639-af6a-cabdb034c05b' }}
            />
        </group>
    )
}

useGLTF.preload('/model/bdtec/electronic.glb')

