/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import {useGLTF} from '@react-three/drei'

export function Roller(props:any) {
    const { nodes, materials }:any = useGLTF('/model/duon/roller.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.tripo_node_f608efc9.geometry}
                material={materials.tripo_mat_f608efc9}
                rotation={[-Math.PI / 2, 0, 0]}
            />
        </group>
    )
}

useGLTF.preload('/model/duon/roller.glb')
