/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import type { Group } from 'three'

export function WorldModel(props) {
    const group = useRef<Group>(null)
    const { nodes, materials, animations } = useGLTF('/model/progist/world.glb')
    const { actions } = useAnimations(animations, group)

    useEffect(() => {
        if (!actions) return

        Object.values(actions).forEach((action) => {
            if (!action) return
            action.reset().fadeIn(0.2).play()
        })

        return () => {
            Object.values(actions).forEach((action) => {
                action?.fadeOut(0.2)
            })
        }
    }, [actions])

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <mesh
                    name="Air_Quality"
                    castShadow
                    receiveShadow
                    geometry={nodes.Air_Quality.geometry}
                    material={materials.A1}
                    position={[20.648, -613.842, 6.875]}
                    scale={[1.094, 1, 1.306]}
                />
                <mesh
                    name="Institution_Promtion_Zone"
                    castShadow
                    receiveShadow
                    geometry={nodes.Institution_Promtion_Zone.geometry}
                    material={materials.A1}
                    position={[20.648, -613.842, 6.875]}
                    scale={[1.094, 1, 1.306]}
                />
                <mesh
                    name="Carbon_Neutrality_Zone"
                    castShadow
                    receiveShadow
                    geometry={nodes.Carbon_Neutrality_Zone.geometry}
                    material={materials.A1}
                    position={[20.648, -613.842, 6.875]}
                    scale={[1.094, 1, 1.306]}
                />
                <mesh
                    name="Water_Quality_Zone"
                    castShadow
                    receiveShadow
                    geometry={nodes.Water_Quality_Zone.geometry}
                    material={materials.A1}
                    position={[20.648, -613.842, 6.875]}
                    scale={[1.094, 1, 1.306]}
                />
                <mesh
                    name="Measurement_Analysis_Zone"
                    castShadow
                    receiveShadow
                    geometry={nodes.Measurement_Analysis_Zone.geometry}
                    material={materials.A1}
                    position={[20.648, -613.842, 6.875]}
                    scale={[1.094, 1, 1.306]}
                />
                <mesh
                    name="Foregin_Pavilion_Zone"
                    castShadow
                    receiveShadow
                    geometry={nodes.Foregin_Pavilion_Zone.geometry}
                    material={materials.A1}
                    position={[20.648, -613.842, 6.875]}
                    scale={[1.094, 1, 1.306]}
                />
                <mesh
                    name="Center"
                    castShadow
                    receiveShadow
                    geometry={nodes.Center.geometry}
                    material={materials.A1}
                    position={[0, -4.238, 0]}
                    scale={[0.686, 0.614, 0.686]}
                />
                <mesh
                    name="Water_all"
                    castShadow
                    receiveShadow
                    geometry={nodes.Water_all.geometry}
                    material={materials.A1}
                    position={[20.406, -90.909, -1.914]}
                >
                    <meshPhysicalMaterial
                        color="#88ccff"       // 맑고 연한 하늘색
                        transmission={0.9}    // 💡 핵심: 유리의 투명도 (1에 가까울수록 완전 투명한 유리)
                        transparent={true}    // 투명 속성 활성화
                        opacity={1}           // transmission을 쓸 때는 opacity를 1로 두는 것이 자연스럽습니다.
                        roughness={0.1}       // 표면의 거칠기 (낮을수록 매끈한 유리/물 표면)
                        metalness={0.1}       // 살짝 반사광을 더해주기 위해 약간만 부여
                        ior={1.33}            // 💡 빛의 굴절률 (1.33은 실제 물의 굴절률, 1.5는 유리입니다)
                        thickness={2.0}       // 굴절의 깊이감 (모델의 두께에 따라 숫자를 조절해 보세요)
                    />
                </mesh>
                <mesh
                    name="Water_Quality_Land"
                    castShadow
                    receiveShadow
                    geometry={nodes.Water_Quality_Land.geometry}
                    material={materials.A1}
                    position={[-128.19, 1.5, 19.602]}
                />
                <mesh
                    name="Foreign_Land"
                    castShadow
                    receiveShadow
                    geometry={nodes.Foreign_Land.geometry}
                    material={materials.A1}
                    position={[86.982, 1.25, -78.103]}
                />
                <mesh
                    name="Institution_Land"
                    castShadow
                    receiveShadow
                    geometry={nodes.Institution_Land.geometry}
                    material={materials.A1}
                    position={[14.794, 1.5, -113.668]}
                />
                <mesh
                    name="Measurement_Land"
                    castShadow
                    receiveShadow
                    geometry={nodes.Measurement_Land.geometry}
                    material={materials.A1}
                    position={[122.27, 1.5, 48.293]}
                />
                <mesh
                    name="Air_Land"
                    castShadow
                    receiveShadow
                    geometry={nodes.Air_Land.geometry}
                    material={materials.A1}
                    position={[-68.156, 1.501, -91.893]}
                />
                <mesh
                    name="Water_building"
                    castShadow
                    receiveShadow
                    geometry={nodes.Water_building.geometry}
                    material={materials.A1}
                    position={[-132.845, 2.908, 37.503]}
                    rotation={[0, -0.262, 0]}
                />
                <mesh
                    name="Moutain_01"
                    castShadow
                    receiveShadow
                    geometry={nodes.Moutain_01.geometry}
                    material={materials.A1}
                    position={[-146.438, 0.071, -37.753]}
                />
                <mesh
                    name="Moutain_02"
                    castShadow
                    receiveShadow
                    geometry={nodes.Moutain_02.geometry}
                    material={materials.A1}
                    position={[-102.551, 0.316, -11.946]}
                />
                <mesh
                    name="Moutain_03"
                    castShadow
                    receiveShadow
                    geometry={nodes.Moutain_03.geometry}
                    material={materials.A1}
                    position={[-67.055, 32.224, -92.454]}
                    rotation={[0, 0.611, 0]}
                />
                <mesh
                    name="Gear_A"
                    castShadow
                    receiveShadow
                    geometry={nodes.Gear_A.geometry}
                    material={materials.A1}
                    position={[-52.23, 24.156, -58.137]}
                    rotation={[0, 0.611, 0]}
                />
                <mesh
                    name="Gear_G"
                    castShadow
                    receiveShadow
                    geometry={nodes.Gear_G.geometry}
                    material={materials.A1}
                    position={[-55.77, 12.127, -55.498]}
                    rotation={[0, 0.611, 0]}
                />
                <mesh
                    name="Gear_D"
                    castShadow
                    receiveShadow
                    geometry={nodes.Gear_D.geometry}
                    material={materials.A1}
                    position={[-41.869, 12.31, -65.633]}
                    rotation={[0, 0.611, 0]}
                />
                <mesh
                    name="Gear_B"
                    castShadow
                    receiveShadow
                    geometry={nodes.Gear_B.geometry}
                    material={materials.A1}
                    position={[-48.511, 12.812, -61.321]}
                    rotation={[0, 0.611, 0]}
                />
                <mesh
                    name="Gear_E"
                    castShadow
                    receiveShadow
                    geometry={nodes.Gear_E.geometry}
                    material={materials.A1}
                    position={[-37.619, 18.769, -68.625]}
                    rotation={[0, 0.611, 0]}
                />
                <mesh
                    name="Frame"
                    castShadow
                    receiveShadow
                    geometry={nodes.Frame.geometry}
                    material={materials.A1}
                    position={[-51.168, 20.767, -60.414]}
                    rotation={[Math.PI / 2, 0, -0.611]}
                />
                <mesh
                    name="Gear_F"
                    castShadow
                    receiveShadow
                    geometry={nodes.Gear_F.geometry}
                    material={materials.A1}
                    position={[-36.271, 7.723, -69.99]}
                    rotation={[0, 0.611, 0]}
                    scale={[1, 1, 0.5]}
                />
                <mesh
                    name="Air_tower"
                    castShadow
                    receiveShadow
                    geometry={nodes.Air_tower.geometry}
                    material={materials.A1}
                    position={[-64.091, 18.78, -42.657]}
                    rotation={[0, 1.265, 0]}
                />
                <mesh
                    name="Air_Fan_A"
                    castShadow
                    receiveShadow
                    geometry={nodes.Air_Fan_A.geometry}
                    material={materials.A1}
                    position={[-43.231, 35.155, -89.368]}
                    rotation={[0, 0.698, 0]}
                    scale={0.572}
                />
                <mesh
                    name="Air_Fan_B"
                    castShadow
                    receiveShadow
                    geometry={nodes.Air_Fan_B.geometry}
                    material={materials.A1}
                    position={[-62.826, 48.247, -91.173]}
                    rotation={[0, 0.611, 0]}
                    scale={[0.419, 0.419, 0.381]}
                />
                <mesh
                    name="Air_Fan_B_propeller"
                    castShadow
                    receiveShadow
                    geometry={nodes.Air_Fan_B_propeller.geometry}
                    material={materials.A1}
                    position={[-48.467, 67.937, -101.219]}
                    rotation={[Math.PI / 2, 0, -0.611]}
                    scale={[0.444, 0.37, 0.444]}
                />
                <mesh
                    name="Air_Fan_A_propeller"
                    castShadow
                    receiveShadow
                    geometry={nodes.Air_Fan_A_propeller.geometry}
                    material={materials.A1}
                    position={[-43.272, 35.113, -89.417]}
                    rotation={[0, 0.698, 0]}
                    scale={0.572}
                />
                <mesh
                    name="Info_Tower"
                    castShadow
                    receiveShadow
                    geometry={nodes.Info_Tower.geometry}
                    material={materials.A1}
                    position={[0, 3.019, 0]}
                />
                <mesh
                    name="Info_Tower_Screen"
                    castShadow
                    receiveShadow
                    geometry={nodes.Info_Tower_Screen.geometry}
                    material={materials.A1}
                    position={[0, 61.829, 0]}
                />
                <mesh
                    name="Bridge"
                    castShadow
                    receiveShadow
                    geometry={nodes.Bridge.geometry}
                    material={materials.A1}
                />
                <mesh
                    name="Korea_Building"
                    castShadow
                    receiveShadow
                    geometry={nodes.Korea_Building.geometry}
                    material={materials.A1}
                    position={[107.691, 2.502, -122.535]}
                    rotation={[0, -0.131, 0]}
                />
                <mesh
                    name="Institution_Builidng"
                    castShadow
                    receiveShadow
                    geometry={nodes.Institution_Builidng.geometry}
                    material={materials.B1}
                    position={[18.061, 29.942, -127.342]}
                    scale={[1.511, 1.035, 1.035]}
                />
                <mesh
                    name="Big_Tree_House"
                    castShadow
                    receiveShadow
                    geometry={nodes.Big_Tree_House.geometry}
                    material={materials.A1}
                    position={[-79.966, 1.762, 206.758]}
                    rotation={[Math.PI / 2, 0, 2.313]}
                    scale={14.993}
                />
                <mesh
                    name="Logo_Text"
                    castShadow
                    receiveShadow
                    geometry={nodes.Logo_Text.geometry}
                    material={materials.B1}
                    position={[18.395, 64.939, -127.55]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={[0.267, 0.224, 0.267]}
                />
                <mesh
                    name="Cart01"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cart01.geometry}
                    material={materials.A1}
                    position={[-16.195, 2.962, 125.86]}
                    rotation={[Math.PI / 2, -0.175, 0]}
                />
                <mesh
                    name="Carbon_Land"
                    castShadow
                    receiveShadow
                    geometry={nodes.Carbon_Land.geometry}
                    material={materials.A1}
                    position={[-6.876, 1.948, 99.247]}
                />
                <mesh
                    name="House_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.House_1.geometry}
                    material={materials.A1}
                    position={[-20.011, 2.916, 97.777]}
                    scale={1.6}
                />
                <mesh
                    name="House_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.House_2.geometry}
                    material={materials.A1}
                    position={[37.972, 2.982, 106.329]}
                    scale={1.387}
                />
                <mesh
                    name="House_3"
                    castShadow
                    receiveShadow
                    geometry={nodes.House_3.geometry}
                    material={materials.A1}
                    position={[-96.504, 22.659, -15.405]}
                    rotation={[Math.PI / 2, 0, 2.793]}
                />
                <mesh
                    name="House_4"
                    castShadow
                    receiveShadow
                    geometry={nodes.House_4.geometry}
                    material={materials.A1}
                    position={[14.548, 2.857, 79.269]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={1.387}
                />
                <mesh
                    name="House_5"
                    castShadow
                    receiveShadow
                    geometry={nodes.House_5.geometry}
                    material={materials.A1}
                    position={[-48.153, 2.857, 132.751]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                    scale={1.387}
                />
                <mesh
                    name="Mill"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mill.geometry}
                    material={materials.A1}
                    position={[-60.93, 2.674, 89.898]}
                    rotation={[Math.PI / 2, 0, -0.611]}
                    scale={2.219}
                />
                <mesh
                    name="Tree_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_1.geometry}
                    material={materials.A1}
                    position={[-20.793, 2.863, -136.042]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={1.977}
                />
                <mesh
                    name="Tree_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_2.geometry}
                    material={materials.A1}
                    position={[4.243, 2.863, -108.042]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={1.977}
                />
                <mesh
                    name="Warehouse01"
                    castShadow
                    receiveShadow
                    geometry={nodes.Warehouse01.geometry}
                    material={materials.A1}
                    position={[25.947, 2.977, 107.255]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={1.387}
                />
                <mesh
                    name="Grass1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Grass1.geometry}
                    material={materials.A1}
                    position={[-69.143, 2.977, 137.999]}
                    scale={0.672}
                />
                <mesh
                    name="Grass2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Grass2.geometry}
                    material={materials.A1}
                    position={[-69.452, 2.96, 135.84]}
                    scale={1.12}
                />
                <mesh
                    name="Mushroom1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mushroom1.geometry}
                    material={materials.A1}
                    position={[-66.978, 2.978, 139.352]}
                />
                <mesh
                    name="Mushroom2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mushroom2.geometry}
                    material={materials.A1}
                    position={[-65.281, 2.978, 137.793]}
                />
                <mesh
                    name="MushroomLarge"
                    castShadow
                    receiveShadow
                    geometry={nodes.MushroomLarge.geometry}
                    material={materials.A1}
                    position={[-65.732, 2.962, 138.814]}
                />
                <mesh
                    name="Rock1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rock1.geometry}
                    material={materials.A1}
                    position={[-62.573, 3.068, 141.25]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.029}
                />
                <mesh
                    name="Rock2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rock2.geometry}
                    material={materials.A1}
                    position={[-72.792, 3.068, 135.891]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.029}
                />
                <mesh
                    name="Rock3"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rock3.geometry}
                    material={materials.A1}
                    position={[-62.173, 3.068, 135.19]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.029}
                />
                <mesh
                    name="Rock4"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rock4.geometry}
                    material={materials.A1}
                    position={[-68.433, 2.651, 54.381]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.029}
                />
                <mesh
                    name="Rock5"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rock5.geometry}
                    material={materials.A1}
                    position={[-55.759, 2.76, 48.526]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.029}
                />
                <mesh
                    name="Rock6"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rock6.geometry}
                    material={materials.A1}
                    position={[-76.07, 3.068, 120.302]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.029}
                />
                <mesh
                    name="Tree_4"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_4.geometry}
                    material={materials.A1}
                    position={[-135.737, 2.849, 78.488]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.033}
                />
                <mesh
                    name="Tree_5"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_5.geometry}
                    material={materials.A1}
                    position={[-127.791, 2.849, -8.14]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.02}
                />
                <mesh
                    name="Tree_6"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_6.geometry}
                    material={materials.A1}
                    position={[-95.238, 2.849, 63.617]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.032}
                />
                <mesh
                    name="Bush_free_01"
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush_free_01.geometry}
                    material={materials.A1}
                    position={[45.107, 2.464, -106.88]}
                    rotation={[Math.PI / 2, 0, -2.443]}
                    scale={0.024}
                />
                <mesh
                    name="Bush_free_02"
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush_free_02.geometry}
                    material={materials.A1}
                    position={[18.106, 4.163, -127.257]}
                />
                <mesh
                    name="Grass_free_01"
                    castShadow
                    receiveShadow
                    geometry={nodes.Grass_free_01.geometry}
                    material={materials.A1}
                    position={[-9.88, 2.816, 128.598]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.077}
                />
                <mesh
                    name="Grass_free_02"
                    castShadow
                    receiveShadow
                    geometry={nodes.Grass_free_02.geometry}
                    material={materials.A1}
                    position={[1.004, 2.816, 140.527]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.077}
                />
                <mesh
                    name="Shrub_A"
                    castShadow
                    receiveShadow
                    geometry={nodes.Shrub_A.geometry}
                    material={materials.A1}
                    position={[128.171, 3.027, 77.026]}
                    rotation={[Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.015}
                />
                <mesh
                    name="TreeType_3"
                    castShadow
                    receiveShadow
                    geometry={nodes.TreeType_3.geometry}
                    material={materials.A1}
                    position={[103.374, 2.958, 90.742]}
                    rotation={[Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.023}
                />
                <mesh
                    name="TreeType_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.TreeType_2.geometry}
                    material={materials.A1}
                    position={[71.185, 3.027, 69.781]}
                    rotation={[Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.015}
                />
                <mesh
                    name="TreeType_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.TreeType_1.geometry}
                    material={materials.A1}
                    position={[125.853, 3.027, 106.963]}
                    rotation={[Math.PI / 2, 0, 1.091]}
                    scale={0.015}
                />
                <mesh
                    name="Building_AA"
                    castShadow
                    receiveShadow
                    geometry={nodes.Building_AA.geometry}
                    material={materials.A1}
                    position={[67.335, 3.068, 51.743]}
                    rotation={[Math.PI / 2, 0, -0.873]}
                    scale={[0.085, 0.085, 0.136]}
                />
                <mesh
                    name="Building_BB"
                    castShadow
                    receiveShadow
                    geometry={nodes.Building_BB.geometry}
                    material={materials.A1}
                    position={[154.585, 2.954, -4.226]}
                />
                <mesh
                    name="sport_store"
                    castShadow
                    receiveShadow
                    geometry={nodes.sport_store.geometry}
                    material={materials.A1}
                    position={[130.356, 2.821, 1.816]}
                />
                <mesh
                    name="studio_video_games"
                    castShadow
                    receiveShadow
                    geometry={nodes.studio_video_games.geometry}
                    material={materials.A1}
                    position={[127.798, 2.867, 88.637]}
                    rotation={[Math.PI / 2, 0, -0.742]}
                    scale={0.085}
                />
                <mesh
                    name="video_games_store"
                    castShadow
                    receiveShadow
                    geometry={nodes.video_games_store.geometry}
                    material={materials.A1}
                    position={[91.705, 2.965, 79.299]}
                />
                <mesh
                    name="Building_C"
                    castShadow
                    receiveShadow
                    geometry={nodes.Building_C.geometry}
                    material={materials.A1}
                    position={[87.13, 2.511, 89.843]}
                />
                <mesh
                    name="Building_D"
                    castShadow
                    receiveShadow
                    geometry={nodes.Building_D.geometry}
                    material={materials.A1}
                    position={[10.53, 2.511, -24.709]}
                    rotation={[0, 0.873, 0]}
                    scale={0.067}
                />
                <mesh
                    name="Building_G"
                    castShadow
                    receiveShadow
                    geometry={nodes.Building_G.geometry}
                    material={materials.A1}
                    position={[170.52, 13.202, -16.343]}
                />
                <mesh
                    name="autumn_tree_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.autumn_tree_2.geometry}
                    material={materials.A1}
                    position={[55.816, 2.638, -70.915]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.016}
                />
                <mesh
                    name="autumn_tree_3"
                    castShadow
                    receiveShadow
                    geometry={nodes.autumn_tree_3.geometry}
                    material={materials.A1}
                    position={[46.974, 2.638, -63.191]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.016}
                />
                <mesh
                    name="autumn_tree_4"
                    castShadow
                    receiveShadow
                    geometry={nodes.autumn_tree_4.geometry}
                    material={materials.A1}
                    position={[99.128, 2.638, -108.136]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 6]}
                    scale={0.016}
                />
                <mesh
                    name="autumn_tree_5"
                    castShadow
                    receiveShadow
                    geometry={nodes.autumn_tree_5.geometry}
                    material={materials.A1}
                    position={[112.74, 2.638, -105.065]}
                    rotation={[Math.PI / 2, 0, 0.436]}
                    scale={0.014}
                />
                <mesh
                    name="autumn_tree"
                    castShadow
                    receiveShadow
                    geometry={nodes.autumn_tree.geometry}
                    material={materials.A1}
                    position={[72.324, 2.638, -106.933]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.016}
                />
                <mesh
                    name="M_building_A"
                    castShadow
                    receiveShadow
                    geometry={nodes.M_building_A.geometry}
                    material={materials.A1}
                    position={[162.151, 2.848, -26.911]}
                />
                <mesh
                    name="Foreign_building_B"
                    castShadow
                    receiveShadow
                    geometry={nodes.Foreign_building_B.geometry}
                    material={materials.A1}
                    position={[176.189, 2.92, -7.461]}
                />
                <mesh
                    name="Foreign_building_C"
                    castShadow
                    receiveShadow
                    geometry={nodes.Foreign_building_C.geometry}
                    material={materials.A1}
                    position={[37.431, 2.654, -47.81]}
                    rotation={[0, 0.916, 0]}
                />
                <mesh
                    name="Foreign_building_D"
                    castShadow
                    receiveShadow
                    geometry={nodes.Foreign_building_D.geometry}
                    material={materials.A1}
                    position={[140.876, 2.654, -70.248]}
                    rotation={[0, -1.353, 0]}
                />
                <mesh
                    name="desert_stone_small_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.desert_stone_small_2.geometry}
                    material={materials.A1}
                    position={[127.351, 2.911, 104.487]}
                />
                <mesh
                    name="desert_stone_small_3"
                    castShadow
                    receiveShadow
                    geometry={nodes.desert_stone_small_3.geometry}
                    material={materials.A1}
                    position={[72.573, 2.911, 71.211]}
                />
                <mesh
                    name="desert_stone_small_4"
                    castShadow
                    receiveShadow
                    geometry={nodes.desert_stone_small_4.geometry}
                    material={materials.A1}
                    position={[71.29, 2.911, 68.56]}
                />
                <mesh
                    name="desert_stone_small_5"
                    castShadow
                    receiveShadow
                    geometry={nodes.desert_stone_small_5.geometry}
                    material={materials.A1}
                    position={[102.716, 2.911, 93.63]}
                />
                <mesh
                    name="desert_stone_small_6"
                    castShadow
                    receiveShadow
                    geometry={nodes.desert_stone_small_6.geometry}
                    material={materials.A1}
                    position={[122.129, 2.911, 108.148]}
                />
                <mesh
                    name="desert_stone_small_7"
                    castShadow
                    receiveShadow
                    geometry={nodes.desert_stone_small_7.geometry}
                    material={materials.A1}
                    position={[102.694, 2.911, 83.95]}
                    rotation={[-Math.PI, 0.873, -Math.PI]}
                />
                <mesh
                    name="japanes_temple"
                    castShadow
                    receiveShadow
                    geometry={nodes.japanes_temple.geometry}
                    material={materials.A1}
                    position={[83.044, 2.654, -121.28]}
                />
                <mesh
                    name="pyramid"
                    castShadow
                    receiveShadow
                    geometry={nodes.pyramid.geometry}
                    material={materials.A1}
                    position={[64.085, 2.504, -29.921]}
                    rotation={[Math.PI, -1.309, Math.PI]}
                />
                <mesh
                    name="sakura_tree"
                    castShadow
                    receiveShadow
                    geometry={nodes.sakura_tree.geometry}
                    material={materials.A1}
                    position={[90.381, 2.638, -105.26]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.016}
                />
                <mesh
                    name="snowman"
                    castShadow
                    receiveShadow
                    geometry={nodes.snowman.geometry}
                    material={materials.A1}
                    position={[-54.573, 2.808, -37.055]}
                    rotation={[Math.PI / 2, 0, -1.265]}
                    scale={0.039}
                />
                <mesh
                    name="sphinx"
                    castShadow
                    receiveShadow
                    geometry={nodes.sphinx.geometry}
                    material={materials.A1}
                    position={[110.676, 2.921, -38.024]}
                    rotation={[0, -1.222, 0]}
                    scale={1.4}
                />
                <mesh
                    name="stone_large_brown_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_large_brown_2.geometry}
                    material={materials.A1}
                    position={[126.693, 2.597, -39.8]}
                    rotation={[Math.PI / 2, 0, 1.658]}
                    scale={[0.019, 0.019, 0.02]}
                />
                <mesh
                    name="stone_large_brown"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_large_brown.geometry}
                    material={materials.A1}
                    position={[121.82, 2.782, -50.807]}
                    rotation={[Math.PI / 2, 0, 0.218]}
                    scale={[0.014, 0.014, 0.026]}
                />
                <mesh
                    name="stone_large_gray_blue_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_large_gray_blue_2.geometry}
                    material={materials.A1}
                    position={[-95.594, 2.897, 70.013]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.017}
                />
                <mesh
                    name="stone_large_gray_blue_3"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_large_gray_blue_3.geometry}
                    material={materials.A1}
                    position={[-150.198, 2.897, 75.673]}
                    rotation={[Math.PI / 2, 0, -2.531]}
                    scale={0.023}
                />
                <mesh
                    name="stone_large_gray_blue_5"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_large_gray_blue_5.geometry}
                    material={materials.A1}
                    position={[32.822, 2.704, 81.138]}
                    rotation={[Math.PI / 2, 0, -0.175]}
                    scale={0.015}
                />
                <mesh
                    name="stone_large_gray_blue"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_large_gray_blue.geometry}
                    material={materials.A1}
                    position={[146.362, 2.891, -46.964]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}
                />
                <mesh
                    name="stone_small_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_small_2.geometry}
                    material={materials.A1}
                    position={[-131.555, 2.852, 75.907]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.031}
                />
                <mesh
                    name="stone_small_3"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_small_3.geometry}
                    material={materials.A1}
                    position={[-99.433, 2.852, 74.613]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.031}
                />
                <mesh
                    name="stone_small_4"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_small_4.geometry}
                    material={materials.A1}
                    position={[-138.896, 2.852, 87.04]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.031}
                />
                <mesh
                    name="stone_small_5"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_small_5.geometry}
                    material={materials.A1}
                    position={[-121.755, 2.852, 106.352]}
                    rotation={[Math.PI / 2, 0, -1.527]}
                    scale={0.031}
                />
                <mesh
                    name="stone_small_6"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_small_6.geometry}
                    material={materials.A1}
                    position={[-115.412, 2.852, 106.021]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.046}
                />
                <mesh
                    name="torii_gate"
                    castShadow
                    receiveShadow
                    geometry={nodes.torii_gate.geometry}
                    material={materials.A1}
                    position={[87.234, 2.749, -29.106]}
                    rotation={[0, Math.PI / 9, 0]}
                />
                <mesh
                    name="Tree_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_0.geometry}
                    material={materials.A1}
                    position={[26.864, 2.863, -107.177]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.026}
                />
                <mesh
                    name="ResidentBuilding_01"
                    castShadow
                    receiveShadow
                    geometry={nodes.ResidentBuilding_01.geometry}
                    material={materials.A1}
                    position={[-67.734, 2.867, 123.2]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                    scale={0.018}
                />
                <mesh
                    name="ResidentBuilding_02"
                    castShadow
                    receiveShadow
                    geometry={nodes.ResidentBuilding_02.geometry}
                    material={materials.A1}
                    position={[-50.357, 2.92, 75.392]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.018}
                />
                <mesh
                    name="ResidentBuilding_03"
                    castShadow
                    receiveShadow
                    geometry={nodes.ResidentBuilding_03.geometry}
                    material={materials.A1}
                    position={[-28.434, 2.91, 136.333]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.018}
                />
                <mesh
                    name="GreenMouse"
                    castShadow
                    receiveShadow
                    geometry={nodes.GreenMouse.geometry}
                    material={materials.A1}
                    position={[15.972, 2.863, 145.752]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.016}
                />
                <mesh
                    name="Radio_01"
                    castShadow
                    receiveShadow
                    geometry={nodes.Radio_01.geometry}
                    material={materials.A1}
                    position={[125.838, 2.918, -13.227]}
                />
                <mesh
                    name="Radio_02"
                    castShadow
                    receiveShadow
                    geometry={nodes.Radio_02.geometry}
                    material={materials.A1}
                    position={[115.472, 2.913, -8.424]}
                />
                <mesh
                    name="Natures_Big_Tree"
                    castShadow
                    receiveShadow
                    geometry={nodes.Natures_Big_Tree.geometry}
                    material={materials.A1}
                    position={[-67.412, 2.724, 137.288]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={2.353}
                />
                <mesh
                    name="Props_Windmill"
                    castShadow
                    receiveShadow
                    geometry={nodes.Props_Windmill.geometry}
                    material={materials.A1}
                    position={[-22.985, 2.886, -70.788]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={1.764}
                />
                <mesh
                    name="A_Building_f"
                    castShadow
                    receiveShadow
                    geometry={nodes.A_Building_f.geometry}
                    material={materials.A1}
                    position={[142.257, 2.87, -19.217]}
                />
                <mesh
                    name="A_Building_g"
                    castShadow
                    receiveShadow
                    geometry={nodes.A_Building_g.geometry}
                    material={materials.A1}
                    position={[85.977, 2.931, 5.709]}
                    rotation={[0, Math.PI / 8, 0]}
                    scale={1.397}
                />
                <mesh
                    name="A_Building_h"
                    castShadow
                    receiveShadow
                    geometry={nodes.A_Building_h.geometry}
                    material={materials.A1}
                    position={[128.657, 2.765, -97.212]}
                    rotation={[Math.PI / 2, 0, -0.567]}
                    scale={1.92}
                />
                <mesh
                    name="Convention_hall_A"
                    castShadow
                    receiveShadow
                    geometry={nodes.Convention_hall_A.geometry}
                    material={materials.A1}
                    position={[104.332, 11.863, 106.558]}
                    rotation={[0, Math.PI / 6, 0]}
                />
                <mesh
                    name="Clock_tower"
                    castShadow
                    receiveShadow
                    geometry={nodes.Clock_tower.geometry}
                    material={materials.A1}
                    position={[136.151, 2.887, -46.081]}
                    rotation={[0, 0.436, 0]}
                />
                <mesh
                    name="Building_B"
                    castShadow
                    receiveShadow
                    geometry={nodes.Building_B.geometry}
                    material={materials.A1}
                    position={[50.778, 6.063, 366.708]}
                    rotation={[Math.PI, -1.222, Math.PI]}
                    scale={0.038}
                />
                <mesh
                    name="Air_tower001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Air_tower001.geometry}
                    material={materials.A1}
                    position={[-54.484, 12.422, -49.541]}
                    rotation={[0, -0.436, 0]}
                    scale={0.6}
                />
                <mesh
                    name="Wing"
                    castShadow
                    receiveShadow
                    geometry={nodes.Wing.geometry}
                    material={materials.A1}
                    position={[-22.158, 29.96, -69.257]}
                    rotation={[-Math.PI / 2, 0.175, -Math.PI]}
                    scale={1.764}
                />
                <mesh
                    name="Props_Windmill001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Props_Windmill001.geometry}
                    material={materials.A1}
                    position={[-13.683, 2.886, -74.776]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={1.764}
                />
                <mesh
                    name="Wing001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Wing001.geometry}
                    material={materials.A1}
                    position={[-17.346, 22.184, -73.245]}
                    rotation={[Math.PI / 2, -0.873, 0]}
                    scale={1.764}
                />
                <mesh
                    name="Props_Windmill002"
                    castShadow
                    receiveShadow
                    geometry={nodes.Props_Windmill002.geometry}
                    material={materials.A1}
                    position={[-17.684, 2.943, -81.03]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={2.382}
                />
                <mesh
                    name="Wing002"
                    castShadow
                    receiveShadow
                    geometry={nodes.Wing002.geometry}
                    material={materials.A1}
                    position={[-17.688, 26.691, -78.964]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={2.382}
                />
                <mesh
                    name="CH_Air002"
                    castShadow
                    receiveShadow
                    geometry={nodes.CH_Air002.geometry}
                    material={materials.A1}
                    position={[-26.059, 2.94, -65.166]}
                    rotation={[0, -0.475, 0]}
                    scale={0.368}
                />
                <mesh
                    name="Bush_free_003"
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush_free_003.geometry}
                    material={materials.A1}
                    position={[-11.392, 2.375, -106.934]}
                    rotation={[Math.PI / 2, 0, -2.967]}
                    scale={0.024}
                />
                <mesh
                    name="Stand"
                    castShadow
                    receiveShadow
                    geometry={nodes.Stand.geometry}
                    material={materials.A1}
                    position={[-2.219, 2.871, -96.833]}
                />
                <mesh
                    name="Lake"
                    castShadow
                    receiveShadow
                    geometry={nodes.Lake.geometry}
                    material={materials.A1}
                    position={[-103.421, 20.011, -25.343]}
                    rotation={[0, 0.916, 0]}
                    scale={[0.319, 1, 0.319]}
                />
                <mesh
                    name="Tree_1_001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_1_001.geometry}
                    material={materials.A1}
                    position={[29.263, 2.863, -148.449]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={2.608}
                />
                <mesh
                    name="Tree_1_002"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_1_002.geometry}
                    material={materials.A1}
                    position={[16.658, 2.863, -146.219]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={2.245}
                />
                <mesh
                    name="Tree_1_003"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_1_003.geometry}
                    material={materials.A1}
                    position={[-2.154, 2.863, -147.791]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={2.475}
                />
                <mesh
                    name="Tree_2_001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_2_001.geometry}
                    material={materials.A1}
                    position={[50.833, 2.863, -109.062]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={1.977}
                />
                <mesh
                    name="Tree_2_002"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_2_002.geometry}
                    material={materials.A1}
                    position={[14.562, 2.863, -65.957]}
                    rotation={[Math.PI / 2, 0, -1.702]}
                    scale={2.589}
                />
                <mesh
                    name="Tree_007"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_007.geometry}
                    material={materials.A1}
                    position={[-3.192, 2.863, -75.347]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.026}
                />
                <mesh
                    name="Tree_1_004"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_1_004.geometry}
                    material={materials.A1}
                    position={[57.076, 2.863, -134.079]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={2.608}
                />
                <mesh
                    name="Bush_free_004"
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush_free_004.geometry}
                    material={materials.A1}
                    position={[-3.574, 2.464, -70.955]}
                    rotation={[1.577, 0.054, -1.889]}
                    scale={0.024}
                />
                <mesh
                    name="Bush_free_005"
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush_free_005.geometry}
                    material={materials.A1}
                    position={[14.005, 2.464, -62.246]}
                    rotation={[1.564, -0.054, 1.253]}
                    scale={0.018}
                />
                <mesh
                    name="Tree_2_003"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_2_003.geometry}
                    material={materials.A1}
                    position={[46.956, 2.863, -98.719]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={[1.977, 1.977, 3.386]}
                />
                <mesh
                    name="Bush_free_006"
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush_free_006.geometry}
                    material={materials.A1}
                    position={[49.582, 2.516, -95.584]}
                    rotation={[Math.PI / 2, 0, 2.443]}
                    scale={0.024}
                />
                <mesh
                    name="Bush_free_007"
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush_free_007.geometry}
                    material={materials.A1}
                    position={[5.945, 2.181, -149.566]}
                    rotation={[Math.PI / 2, 0, -2.749]}
                    scale={0.037}
                />
                <mesh
                    name="Bush_free_008"
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush_free_008.geometry}
                    material={materials.A1}
                    position={[35.507, 2.181, -148.725]}
                    rotation={[Math.PI / 2, 0, 0.916]}
                    scale={0.028}
                />
                <mesh
                    name="Bush_free_009"
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush_free_009.geometry}
                    material={materials.A1}
                    position={[14.604, 2.375, -150.616]}
                    rotation={[Math.PI / 2, 0, 0.305]}
                    scale={0.024}
                />
                <mesh
                    name="Tree_D"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_D.geometry}
                    material={materials.A1}
                    position={[-71.132, 2.312, 113.47]}
                />
                <mesh
                    name="Tree_008"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_008.geometry}
                    material={materials.A1}
                    position={[-115.655, 20.116, -35.263]}
                    rotation={[Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.023}
                />
                <mesh
                    name="Tree_016"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_016.geometry}
                    material={materials.A1}
                    position={[-131.204, 21.667, -57.951]}
                    rotation={[Math.PI / 2, 0, 0.567]}
                    scale={0.023}
                />
                <mesh
                    name="Tree_017"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_017.geometry}
                    material={materials.A1}
                    position={[-169.666, 2.73, 10.256]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.034}
                />
                <mesh
                    name="Tree_018"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_018.geometry}
                    material={materials.A1}
                    position={[-96.572, 2.849, 21.205]}
                    rotation={[Math.PI / 2, 0, -1.396]}
                    scale={0.025}
                />
                <mesh
                    name="tree_s"
                    castShadow
                    receiveShadow
                    geometry={nodes.tree_s.geometry}
                    material={materials.A1}
                    position={[-115.655, 20.116, -35.263]}
                    rotation={[Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.023}
                />
                <mesh
                    name="CH_Water001"
                    castShadow
                    receiveShadow
                    geometry={nodes.CH_Water001.geometry}
                    material={materials.A1}
                    position={[-106.631, 3.103, 69.976]}
                    rotation={[0, -Math.PI / 4, 0]}
                    scale={[0.985, 1.001, 0.987]}
                />
                <mesh
                    name="stone_large_gray_blue_007"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_large_gray_blue_007.geometry}
                    material={materials.A1}
                    position={[-118.183, 2.411, -17.302]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={[0.035, 0.035, 0.026]}
                />
                <mesh
                    name="Bush_free_010"
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush_free_010.geometry}
                    material={materials.A1}
                    position={[-133.746, 2.464, 80.609]}
                    rotation={[1.625, -0.002, 2.911]}
                    scale={0.018}
                />
                <mesh
                    name="Bush_free_011"
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush_free_011.geometry}
                    material={materials.A1}
                    position={[-94.702, 2.464, 75.219]}
                    rotation={[1.625, -0.002, 2.911]}
                    scale={0.018}
                />
                <mesh
                    name="Bush_free_012"
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush_free_012.geometry}
                    material={materials.A1}
                    position={[-117.666, 2.464, 111.632]}
                    rotation={[1.522, -0.023, 0.249]}
                    scale={0.025}
                />
                <mesh
                    name="Bush_free_013"
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush_free_013.geometry}
                    material={materials.A1}
                    position={[-143.999, 2.464, 92.3]}
                    rotation={[1.625, -0.002, 2.911]}
                    scale={[0.014, 0.015, 0.018]}
                />
                <mesh
                    name="Bush_free_014"
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush_free_014.geometry}
                    material={materials.A1}
                    position={[-152.029, 2.464, 83.391]}
                    rotation={[1.589, 0.051, -2.107]}
                    scale={[0.014, 0.015, 0.018]}
                />
                <mesh
                    name="stone"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone.geometry}
                    material={materials.A1}
                    position={[-19.666, 2.852, -57.807]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.052}
                />
                <mesh
                    name="stone_small_7"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_small_7.geometry}
                    material={materials.A1}
                    position={[-84.633, 2.852, -19.487]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.031}
                />
                <mesh
                    name="Tree_A"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_A.geometry}
                    material={materials.A1}
                    position={[-62.541, 2.312, 48.414]}
                />
                <mesh
                    name="Tree_B"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_B.geometry}
                    material={materials.A1}
                    position={[72.961, 2.312, 138.087]}
                />
                <mesh
                    name="Tree_C"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tree_C.geometry}
                    material={materials.A1}
                    position={[51.154, 2.312, 75.078]}
                    rotation={[0, 1.178, 0]}
                />
                <mesh
                    name="Mill__Wing"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mill__Wing.geometry}
                    material={materials.A1}
                    position={[-60.93, 2.674, 89.898]}
                    rotation={[Math.PI / 2, 0, -0.611]}
                    scale={2.219}
                />
                <mesh
                    name="Carbon_Land001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Carbon_Land001.geometry}
                    material={materials.A1}
                    position={[-23.971, 3.063, 122.831]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    name="stone_large_gray_blue_008"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_large_gray_blue_008.geometry}
                    material={materials.A1}
                    position={[-67.907, 2.811, 37.378]}
                    rotation={[Math.PI / 2, 0, -2.531]}
                    scale={0.023}
                />
                <mesh
                    name="stone_large_gray_blue_009"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_large_gray_blue_009.geometry}
                    material={materials.A1}
                    position={[60.887, 2.889, 107.199]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.017}
                />
                <mesh
                    name="stone_small_010"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_small_010.geometry}
                    material={materials.A1}
                    position={[46.162, 2.844, 152.561]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.031}
                />
                <mesh
                    name="stone_small_011"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_small_011.geometry}
                    material={materials.A1}
                    position={[69.231, 2.844, 141.553]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.031}
                />
                <mesh
                    name="stone_small_012"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_small_012.geometry}
                    material={materials.A1}
                    position={[76.408, 2.844, 134.545]}
                    rotation={[Math.PI / 2, 0, -1.527]}
                    scale={0.031}
                />
                <mesh
                    name="stone_small_013"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_small_013.geometry}
                    material={materials.A1}
                    position={[54.97, 2.774, 127.244]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.046}
                />
                <mesh
                    name="Natures_Big_Tree001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Natures_Big_Tree001.geometry}
                    material={materials.A1}
                    position={[56.074, 2.724, 118.753]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={3.766}
                />
                <mesh
                    name="Natures_Big_Tree002"
                    castShadow
                    receiveShadow
                    geometry={nodes.Natures_Big_Tree002.geometry}
                    material={materials.A1}
                    position={[-49.288, 2.724, 60.9]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={3.059}
                />
                <mesh
                    name="Natures_Big_Tree003"
                    castShadow
                    receiveShadow
                    geometry={nodes.Natures_Big_Tree003.geometry}
                    material={materials.A1}
                    position={[-37.932, 2.724, 73.145]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={2.353}
                />
                <mesh
                    name="Natures_Big_Tree004"
                    castShadow
                    receiveShadow
                    geometry={nodes.Natures_Big_Tree004.geometry}
                    material={materials.A1}
                    position={[-63.465, 2.724, 70.465]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={2.118}
                />
                <mesh
                    name="Natures_Big_Tree005"
                    castShadow
                    receiveShadow
                    geometry={nodes.Natures_Big_Tree005.geometry}
                    material={materials.A1}
                    position={[-27.406, 2.724, 64.251]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={2.353}
                />
                <mesh
                    name="Natures_Big_Tree006"
                    castShadow
                    receiveShadow
                    geometry={nodes.Natures_Big_Tree006.geometry}
                    material={materials.A1}
                    position={[-26.947, 2.724, 83.227]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={2.118}
                />
                <mesh
                    name="Rock007"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rock007.geometry}
                    material={materials.A1}
                    position={[-54.658, 3.068, 59.274]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.029}
                />
                <mesh
                    name="Rock008"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rock008.geometry}
                    material={materials.A1}
                    position={[-60.301, 3.068, 73.004]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.029}
                />
                <mesh
                    name="Rock009"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rock009.geometry}
                    material={materials.A1}
                    position={[-48.244, 3.068, 65.881]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.029}
                />
                <mesh
                    name="stone_small_014"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_small_014.geometry}
                    material={materials.A1}
                    position={[-29.754, 2.844, 75.601]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.031}
                />
                <mesh
                    name="stone_small_015"
                    castShadow
                    receiveShadow
                    geometry={nodes.stone_small_015.geometry}
                    material={materials.A1}
                    position={[-13.414, 2.844, 67.448]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.046}
                />
                <mesh
                    name="GreenMouse001"
                    castShadow
                    receiveShadow
                    geometry={nodes.GreenMouse001.geometry}
                    material={materials.A1}
                    position={[35.537, 2.863, 145.752]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.016}
                />
                <mesh
                    name="Natures_Big_Tree007"
                    castShadow
                    receiveShadow
                    geometry={nodes.Natures_Big_Tree007.geometry}
                    material={materials.A1}
                    position={[52.093, 2.724, 148.497]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={2.636}
                />
                <mesh
                    name="Carbon_Land001_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Carbon_Land001_1.geometry}
                    material={materials.A1}
                    position={[-11.348, 3.063, 148.446]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    name="autumn_tree_006"
                    castShadow
                    receiveShadow
                    geometry={nodes.autumn_tree_006.geometry}
                    material={materials.A1}
                    position={[149.164, 2.638, -50.212]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 6]}
                    scale={0.021}
                />
                <mesh
                    name="autumn_tree_007"
                    castShadow
                    receiveShadow
                    geometry={nodes.autumn_tree_007.geometry}
                    material={materials.A1}
                    position={[82.236, 2.638, -18.688]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 6]}
                    scale={0.014}
                />
                <mesh
                    name="Building_D001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Building_D001.geometry}
                    material={materials.A1}
                    position={[17.479, 2.511, -33.604]}
                    rotation={[0, 0.873, 0]}
                    scale={0.067}
                />
                <mesh
                    name="Stand001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Stand001.geometry}
                    material={materials.A1}
                    position={[97.806, 2.604, -73.447]}
                />
                <mesh
                    name="autumn_tree_008"
                    castShadow
                    receiveShadow
                    geometry={nodes.autumn_tree_008.geometry}
                    material={materials.A1}
                    position={[41.444, 2.638, -21.001]}
                    rotation={[Math.PI / 2, 0, -0.044]}
                    scale={0.021}
                />
                <mesh
                    name="autumn_tree_009"
                    castShadow
                    receiveShadow
                    geometry={nodes.autumn_tree_009.geometry}
                    material={materials.A1}
                    position={[24.174, 2.638, -37.28]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.016}
                />
                <mesh
                    name="autumn_tree_010"
                    castShadow
                    receiveShadow
                    geometry={nodes.autumn_tree_010.geometry}
                    material={materials.A1}
                    position={[29.173, 2.638, -34.823]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.016}
                />
                <mesh
                    name="A_Building_f001"
                    castShadow
                    receiveShadow
                    geometry={nodes.A_Building_f001.geometry}
                    material={materials.A1}
                    position={[151.329, 2.87, -23.387]}
                />
                <mesh
                    name="A_Building_c"
                    castShadow
                    receiveShadow
                    geometry={nodes.A_Building_c.geometry}
                    material={materials.A1}
                    position={[178.627, 2.954, 4.44]}
                />
                <mesh
                    name="TreeType_004"
                    castShadow
                    receiveShadow
                    geometry={nodes.TreeType_004.geometry}
                    material={materials.A1}
                    position={[101.963, 3.027, 123.772]}
                    rotation={[Math.PI / 2, 0, -2.313]}
                    scale={0.019}
                />
                <mesh
                    name="TreeType_005"
                    castShadow
                    receiveShadow
                    geometry={nodes.TreeType_005.geometry}
                    material={materials.A1}
                    position={[100.548, 2.958, 85.328]}
                    rotation={[Math.PI / 2, 0, -3.011]}
                    scale={0.016}
                />
                <mesh
                    name="TreeType_006"
                    castShadow
                    receiveShadow
                    geometry={nodes.TreeType_006.geometry}
                    material={materials.A1}
                    position={[179.353, 3.027, 20.733]}
                    rotation={[Math.PI / 2, 0, -2.313]}
                    scale={0.019}
                />
                <mesh
                    name="TreeType_007"
                    castShadow
                    receiveShadow
                    geometry={nodes.TreeType_007.geometry}
                    material={materials.A1}
                    position={[74.607, 2.958, 12.62]}
                    rotation={[Math.PI / 2, 0, -3.011]}
                    scale={0.016}
                />
                <mesh
                    name="TreeType_008"
                    castShadow
                    receiveShadow
                    geometry={nodes.TreeType_008.geometry}
                    material={materials.A1}
                    position={[102.393, 3.027, -7.589]}
                    rotation={[Math.PI / 2, 0, -1.265]}
                    scale={0.015}
                />
                <mesh
                    name="TreeType_009"
                    castShadow
                    receiveShadow
                    geometry={nodes.TreeType_009.geometry}
                    material={materials.A1}
                    position={[108.648, 3.027, -5.779]}
                    rotation={[Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.015}
                />
                <mesh
                    name="TreeType_010"
                    castShadow
                    receiveShadow
                    geometry={nodes.TreeType_010.geometry}
                    material={materials.A1}
                    position={[72.79, 2.958, 25.429]}
                    rotation={[Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.023}
                />
                <mesh
                    name="TreeType_011"
                    castShadow
                    receiveShadow
                    geometry={nodes.TreeType_011.geometry}
                    material={materials.A1}
                    position={[134.112, 3.027, -14.803]}
                    rotation={[Math.PI / 2, 0, 1.091]}
                    scale={0.012}
                />
                <mesh
                    name="desert_stone_small_008"
                    castShadow
                    receiveShadow
                    geometry={nodes.desert_stone_small_008.geometry}
                    material={materials.A1}
                    position={[110.536, 2.911, -4.93]}
                />
                <mesh
                    name="desert_stone_small_009"
                    castShadow
                    receiveShadow
                    geometry={nodes.desert_stone_small_009.geometry}
                    material={materials.A1}
                    position={[104.963, 2.911, -8.615]}
                />
                <mesh
                    name="desert_stone_small_010"
                    castShadow
                    receiveShadow
                    geometry={nodes.desert_stone_small_010.geometry}
                    material={materials.A1}
                    position={[75.192, 2.911, 24.589]}
                    rotation={[0, Math.PI / 4, 0]}
                />
                <mesh
                    name="desert_stone_small_011"
                    castShadow
                    receiveShadow
                    geometry={nodes.desert_stone_small_011.geometry}
                    material={materials.A1}
                    position={[76.902, 2.419, 11.997]}
                    rotation={[Math.PI, -1.004, Math.PI]}
                />
                <mesh
                    name="Convention_hall_B"
                    castShadow
                    receiveShadow
                    geometry={nodes.Convention_hall_B.geometry}
                    material={materials.A1}
                    position={[156.407, 2.916, 57.671]}
                />
                <mesh
                    name="TreeType_012"
                    castShadow
                    receiveShadow
                    geometry={nodes.TreeType_012.geometry}
                    material={materials.A1}
                    position={[172.036, 2.958, 49.234]}
                    rotation={[Math.PI / 2, 0, -3.011]}
                    scale={0.016}
                />
                <mesh
                    name="TreeType_013"
                    castShadow
                    receiveShadow
                    geometry={nodes.TreeType_013.geometry}
                    material={materials.A1}
                    position={[168.665, 2.958, 51.992]}
                    rotation={[Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.023}
                />
                <mesh
                    name="TreeType_014"
                    castShadow
                    receiveShadow
                    geometry={nodes.TreeType_014.geometry}
                    material={materials.A1}
                    position={[153.09, 3.027, 71.444]}
                    rotation={[Math.PI / 2, 0, -1.92]}
                    scale={0.015}
                />
                <mesh
                    name="autumn_tree_011"
                    castShadow
                    receiveShadow
                    geometry={nodes.autumn_tree_011.geometry}
                    material={materials.A1}
                    position={[130.281, 2.638, -82.325]}
                    rotation={[Math.PI / 2, 0, 0.175]}
                    scale={0.016}
                />
                <mesh
                    name="desert_stone_small_012"
                    castShadow
                    receiveShadow
                    geometry={nodes.desert_stone_small_012.geometry}
                    material={materials.A1}
                    position={[168.725, 2.966, 54.568]}
                    scale={[0.873, 1.176, 0.873]}
                />
                <mesh
                    name="desert_stone_small_013"
                    castShadow
                    receiveShadow
                    geometry={nodes.desert_stone_small_013.geometry}
                    material={materials.A1}
                    position={[172.734, 2.928, 47.605]}
                    scale={[1, 0.673, 1]}
                />
                <mesh
                    name="TreeType_015"
                    castShadow
                    receiveShadow
                    geometry={nodes.TreeType_015.geometry}
                    material={materials.A1}
                    position={[151.415, 3.027, 40.514]}
                    rotation={[Math.PI / 2, 0, -2.313]}
                    scale={0.019}
                />
                <mesh
                    name="TreeType_016"
                    castShadow
                    receiveShadow
                    geometry={nodes.TreeType_016.geometry}
                    material={materials.A1}
                    position={[108.18, 3.027, 62.1]}
                    rotation={[Math.PI / 2, 0, 1.091]}
                    scale={0.015}
                />
                <mesh
                    name="M_Stand"
                    castShadow
                    receiveShadow
                    geometry={nodes.M_Stand.geometry}
                    material={materials.A1}
                    position={[123.44, 2.804, 37.843]}
                />
                <mesh
                    name="A_Building_g_a"
                    castShadow
                    receiveShadow
                    geometry={nodes.A_Building_g_a.geometry}
                    material={materials.A1}
                    position={[85.977, 2.931, 5.709]}
                    rotation={[0, Math.PI / 8, 0]}
                    scale={1.397}
                />
                <mesh
                    name="Big_Tree_House_A"
                    castShadow
                    receiveShadow
                    geometry={nodes.Big_Tree_House_A.geometry}
                    material={materials.A1}
                    position={[-79.966, 1.762, 206.758]}
                    rotation={[Math.PI / 2, 0, 2.313]}
                    scale={14.993}
                />
                <mesh
                    name="Radio_01_A"
                    castShadow
                    receiveShadow
                    geometry={nodes.Radio_01_A.geometry}
                    material={materials.A1}
                    position={[125.838, 2.612, -13.227]}
                />
                <mesh
                    name="Gear_C"
                    castShadow
                    receiveShadow
                    geometry={nodes.Gear_C.geometry}
                    material={materials.A1}
                    position={[-45.301, 19.314, -63.568]}
                    rotation={[0, 0.611, 0]}
                />
                <mesh
                    name="video_games_store_a"
                    castShadow
                    receiveShadow
                    geometry={nodes.video_games_store_a.geometry}
                    material={materials.A1}
                    position={[91.705, 2.965, 79.299]}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/model/progist/world.glb')
