import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="ko">
        <body id="root">
        {/* 일반적인 HTML/React 컴포넌트들이 렌더링되는 영역 */}
        {children}

        {/* 모든 페이지 뒤에 항상 떠 있는 단일 3D 캔버스 */}
        {/*<GlobalCanvas/>*/}
        </body>
        </html>
    );
}