/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Apartment(props:any) {
    const { nodes, materials }:any = useGLTF('/model/duon/Apartment.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Apartment.geometry}
                material={materials.White}
            />
        </group>
    )

}

useGLTF.preload('/model/duon/Apartment.glb')
