/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function FactoryModel(props:any) {
    const { nodes, materials }:any = useGLTF('/model/duon/Factory.glb')
    return (
        <group {...props} dispose={null}>
            <mesh castShadow receiveShadow geometry={nodes.Factory.geometry} material={materials.White} />
        </group>
    )
}

useGLTF.preload('/model/duon/Factory.glb')
