/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from "three";
import {useFrame} from "@react-three/fiber";
import {easing} from "maath";

export function DataModel(props:any) {
    const { nodes, materials }:any = useGLTF('/model/bdtec/data.glb');

    const data:any = useRef(null)


    useFrame((state:any, delta:number) => {
        const t = (1 + Math.sin(state.clock.elapsedTime * 2)) / 2
// 약간의 G를 섞고, B는 5에서 20 사이로 변함
        data.current.color.setRGB(0, 0.5, 5 + t * 15)


    })

    return (
        <group {...props} dispose={null}>
            <group scale={0.01}>
                <group rotation={[0,-Math.PI/2,0]} position={[200, 150, 54.371]}scale={[2,2,2]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Boolean.geometry}
                        material={materials['Material_3.001']}
                        position={[0, -4.833, -1.763]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Rectangle_2.geometry}
                        material={materials.Material_5}
                        position={[0, 5.658, 66.135]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Rectangle_3.geometry}
                        material={materials.Material_5}
                        position={[0, -74.291, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Rectangle_5.geometry}
                        material={materials.Material_5}
                        position={[5.799, 2.356, 71.22]}
                        rotation={[0, 0, 1.847]}
                        scale={[0.648, 0.66, 0.823]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Rectangle_5001.geometry}
                        material={materials.Material_5}
                        position={[-5.787, 2.265, 71.22]}
                        rotation={[0, 0, -0.263]}
                        scale={[0.648, 0.66, 0.823]}
                    />
                </group>
              
                <group rotation={[0,-Math.PI/2,0]} position={[-125.42, 194.59, -86.112]}>
                    <group position={[-48.668, 24.82, -40.987]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder_11.geometry}
                            material={materials['Material_3.001']}
                            position={[0, 14.403, -0.805]}
                            rotation={[Math.PI / 2, 0.698, 0]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder_12.geometry}
                            material={materials['Material_1.001']}
                            position={[0, 14.403, -0.805]}
                            rotation={[-Math.PI / 2, 0, Math.PI]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder_13.geometry}
                            material={materials['Material_2.001']}
                            position={[0.06, 14.445, -0.805]}
                            rotation={[-Math.PI / 2, 0.873, Math.PI]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Rectangle_28.geometry}
                            material={materials['Material_1.001']}
                            position={[0, 0, -6.611]}
                        />
                    </group>
                    <group position={[0, -9.474, 26.208]}>
                        <group position={[45.161, -12.625, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube_11.geometry}
                                material={materials['Material_2.001']}
                                position={[34.671, 34.621, -2.558]}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube_12.geometry}
                                material={materials['Material_2.001']}
                                position={[-34.671, 34.621, -2.558]}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube_13.geometry}
                                material={materials['Material_2.001']}
                                position={[-34.671, -34.621, -2.558]}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube_13001.geometry}
                                material={materials['Material_2.001']}
                                position={[34.671, -34.621, -2.558]}
                            />
                            <group
                                position={[-0.003, -0.001, 5.657]}
                                rotation={[Math.PI / 2, 0, 0]}
                                scale={1.608}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Rectangle_4.geometry}
                                    material={materials['Material_4.001']}
                                    position={[0, -6.588, 0]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                />
                            </group>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Rectangle_25.geometry}
                                material={materials['Material_2.001']}
                                position={[-0.003, -0.001, -1.42]}
                            />
                        </group>
                        <group position={[-49.301, -7.655, -2.94]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Rectangle_25001.geometry}
                                material={materials['Material_2.001']}
                                position={[6.751, 0.756, -2]}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Rectangle_26.geometry}
                                material={materials['Material_2.001']}
                                position={[0, -20.297, -2]}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Rectangle_27.geometry}
                                material={materials['Material_2.001']}
                                position={[6.751, 20.297, -2]}
                            />
                        </group>
                        <group position={[-84.705, 52.782, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Mesh_13001.geometry}
                                material={materials['Material_2.001']}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Mesh_13002.geometry}
                                material={materials['Material_2.001']}
                                position={[10, 0, 0]}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Mesh_13003.geometry}
                                material={materials['Material_2.001']}
                                position={[20, 0, 0]}
                            />
                        </group>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Rectangle_24.geometry}
                            material={materials['Material_3.001']}
                            position={[-0.186, 52.782, -4]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Rectangle_24001.geometry}
                            material={materials['Material_1.001']}
                            position={[0, 0, -12]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere.geometry}
                            material={materials['Material_2.001']}
                            position={[-84.705, 52.782, 0]}
                        />
                    </group>
                </group>
                <mesh rotation={[0,-Math.PI/2,0]}
                    castShadow
                    receiveShadow
                    geometry={nodes.Signboard001.geometry}
                    material={materials['Material_0.001']}
                    position={[-139.146, 0, -53.122]}
                    scale={405.83}
                />
            </group>
            <group position={[2.1, 2.5, 0.75]} scale={[1.8,1.8,1.8,]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.DB_disk_A.geometry}
                    material={materials.White_object}
                    position={[0, 0.01, -0.12]}
                    scale={[0.64, 0.54, 0.66]}
                >
                    <meshPhysicalMaterial
                        ref={data}
                        toneMapped={false}
                        transparent={true}
                        opacity={1}
                    />
                </mesh>
            </group>
        </group>
    )
}

useGLTF.preload('/model/bdtec/data.glb')
